In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
file ="F:/xyz/dataset.csv"
df = pd.read_csv(file)
print(df)

              Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       01-12-2008   Albury     13.4     22.9       0.6          NaN
1       02-12-2008   Albury      7.4     25.1       0.0          NaN
2       03-12-2008   Albury     12.9     25.7       0.0          NaN
3       04-12-2008   Albury      9.2     28.0       0.0          NaN
4       05-12-2008   Albury     17.5     32.3       1.0          NaN
...            ...      ...      ...      ...       ...          ...
145455  21-06-2017    Uluru      2.8     23.4       0.0          NaN
145456  22-06-2017    Uluru      3.6     25.3       0.0          NaN
145457  23-06-2017    Uluru      5.4     26.9       0.0          NaN
145458  24-06-2017    Uluru      7.8     27.0       0.0          NaN
145459  25-06-2017    Uluru     14.9      NaN       0.0          NaN

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W           44.0          W  ...        71.0
1            NaN         WNW           44.0        NNW  ...        44.0
2            NaN         WSW           46.0          W  ...        38.0
3            NaN          NE           24.0         SE  ...        45.0
4            NaN           W           41.0        ENE  ...        82.0
...          ...         ...            ...        ...  ...         ...
145455       NaN           E           31.0         SE  ...        51.0
145456       NaN         NNW           22.0         SE  ...        56.0
145457       NaN           N           37.0         SE  ...        53.0
145458       NaN          SE           28.0        SSE  ...        51.0
145459       NaN         NaN            NaN        ESE  ...        62.0

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9
1              25.0       1010.6       1007.8       NaN       NaN     17.2
2              30.0       1007.6       1008.7       NaN       2.0     21.0
3              16.0       1017.6       1012.8       NaN       NaN     18.1
4              33.0       1010.8       1006.0       7.0       8.0     17.8
...             ...          ...          ...       ...       ...      ...
145455         24.0       1024.6       1020.3       NaN       NaN     10.1
145456         21.0       1023.5       1019.1       NaN       NaN     10.9
145457         24.0       1021.0       1016.8       NaN       NaN     12.5
145458         24.0       1019.4       1016.5       3.0       2.0     15.1
145459         36.0       1020.2       1017.9       8.0       8.0     15.0

        Temp3pm  RainToday  RainTomorrow
0          21.8         No            No
1          24.3         No            No
2          23.2         No            No
3          26.5         No            No
4          29.7         No            No
...         ...        ...           ...
145455     22.4         No            No
145456     24.5         No            No
145457     26.1         No            No
145458     26.0         No            No
145459     20.9         No           NaN

[145460 rows x 23 columns]

In [18]:
# Display basic information about the DataFrame
print(df.info())

# Display summary statistics
print(df.describe())

# Check for missing values
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB
None
             MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000
mean       12.194034      23.221348       2.360918      5.468232
std         6.398495       7.119049       8.478060      4.193704
min        -8.500000      -4.800000       0.000000      0.000000
25%         7.600000      17.900000       0.000000      2.600000
50%        12.000000      22.600000       0.000000      4.800000
75%        16.900000      28.200000       0.800000      7.400000
max        33.900000      48.100000     371.000000    145.000000

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000
mean       7.611178      40.035230      14.043426      18.662657
std        3.785483      13.607062       8.915375       8.809800
min        0.000000       6.000000       0.000000       0.000000
25%        4.800000      31.000000       7.000000      13.000000
50%        8.400000      39.000000      13.000000      19.000000
75%       10.600000      48.000000      19.000000      24.000000
max       14.500000     135.000000     130.000000      87.000000

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000
mean       68.880831      51.539116    1017.64994    1015.255889
std        19.029164      20.795902       7.10653       7.037414
min         0.000000       0.000000     980.50000     977.100000
25%        57.000000      37.000000    1012.90000    1010.400000
50%        70.000000      52.000000    1017.60000    1015.200000
75%        83.000000      66.000000    1022.40000    1020.000000
max       100.000000     100.000000    1041.00000    1039.600000

           Cloud9am      Cloud3pm        Temp9am       Temp3pm
count  89572.000000  86102.000000  143693.000000  141851.00000
mean       4.447461      4.509930      16.990631      21.68339
std        2.887159      2.720357       6.488753       6.93665
min        0.000000      0.000000      -7.200000      -5.40000
25%        1.000000      2.000000      12.300000      16.60000
50%        5.000000      5.000000      16.700000      21.10000
75%        7.000000      7.000000      21.600000      26.40000
max        9.000000      9.000000      40.200000      46.70000
Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [19]:
# Drop rows with missing values
df = df.dropna()

# Alternatively, impute missing values
# df = df.fillna(df.mean())

In [20]:
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
6049,01-01-2009,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0,ENE,...,20.0,13.0,1006.3,1004.4,2.0,5.0,26.6,33.4,No,No
6050,02-01-2009,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0,SSE,...,30.0,8.0,1012.9,1012.1,1.0,1.0,20.3,27.0,No,No
6052,04-01-2009,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0,NNE,...,42.0,22.0,1012.3,1009.2,1.0,6.0,28.7,34.9,No,No
6053,05-01-2009,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0,WNW,...,37.0,22.0,1012.7,1009.1,1.0,5.0,29.1,35.6,No,No
6054,06-01-2009,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0,NW,...,19.0,15.0,1010.7,1007.4,1.0,6.0,33.6,37.6,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,20-06-2017,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0,SE,...,63.0,32.0,1013.9,1010.5,0.0,1.0,24.5,32.3,No,No
142299,21-06-2017,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0,SE,...,56.0,28.0,1014.6,1011.2,7.0,0.0,24.8,32.0,No,No
142300,22-06-2017,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0,E,...,46.0,23.0,1015.3,1011.8,0.0,0.0,24.8,32.1,No,No
142301,23-06-2017,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0,SE,...,62.0,58.0,1014.9,1010.7,1.0,1.0,24.8,29.2,No,No
142302,24-06-2017,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0,ENE,...,73.0,32.0,1013.9,1009.7,6.0,5.0,25.4,31.0,No,No

In [21]:
df = pd.get_dummies(df, columns=['WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow'], drop_first=True)

In [22]:
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,...,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,RainToday_Yes,RainTomorrow_Yes
6049,01-01-2009,Cobar,17.9,35.2,0.0,12.0,12.3,48.0,6.0,20.0,...,False,False,False,False,True,False,False,False,False,False
6050,02-01-2009,Cobar,18.4,28.9,0.0,14.8,13.0,37.0,19.0,19.0,...,False,False,True,False,False,False,False,False,False,False
6052,04-01-2009,Cobar,19.4,37.6,0.0,10.8,10.6,46.0,30.0,15.0,...,False,False,False,False,False,False,False,False,False,False
6053,05-01-2009,Cobar,21.9,38.4,0.0,11.4,12.2,31.0,6.0,6.0,...,False,False,False,False,False,False,False,True,False,False
6054,06-01-2009,Cobar,24.2,41.0,0.0,11.2,8.4,35.0,17.0,13.0,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,20-06-2017,Darwin,19.3,33.4,0.0,6.0,11.0,35.0,9.0,20.0,...,False,False,False,False,False,False,False,False,False,False
142299,21-06-2017,Darwin,21.2,32.6,0.0,7.6,8.6,37.0,13.0,11.0,...,False,True,False,False,False,False,False,False,False,False
142300,22-06-2017,Darwin,20.7,32.8,0.0,5.6,11.0,33.0,17.0,11.0,...,False,False,False,False,False,True,False,False,False,False
142301,23-06-2017,Darwin,19.5,31.8,0.0,6.2,10.6,26.0,9.0,17.0,...,False,False,False,False,False,False,False,False,False,False
142302,24-06-2017,Darwin,20.2,31.7,0.0,5.6,10.7,30.0,15.0,7.0,...,False,False,False,False,False,False,False,False,False,False

In [33]:
from sklearn.preprocessing import LabelEncoder

# Assuming 'df' is your DataFrame and 'Location' is the column to be encoded
le = LabelEncoder()
df['Location'] = le.fit_transform(df['Location'])
print(df)

              Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
6049    01-01-2009         4     17.9     35.2       0.0         12.0
6050    02-01-2009         4     18.4     28.9       0.0         14.8
6052    04-01-2009         4     19.4     37.6       0.0         10.8
6053    05-01-2009         4     21.9     38.4       0.0         11.4
6054    06-01-2009         4     24.2     41.0       0.0         11.2
...            ...       ...      ...      ...       ...          ...
142298  20-06-2017         6     19.3     33.4       0.0          6.0
142299  21-06-2017         6     21.2     32.6       0.0          7.6
142300  22-06-2017         6     20.7     32.8       0.0          5.6
142301  23-06-2017         6     19.5     31.8       0.0          6.2
142302  24-06-2017         6     20.2     31.7       0.0          5.6

        Sunshine  WindGustSpeed  WindSpeed9am  WindSpeed3pm  ...  \
6049        12.3           48.0           6.0          20.0  ...
6050        13.0           37.0          19.0          19.0  ...
6052        10.6           46.0          30.0          15.0  ...
6053        12.2           31.0           6.0           6.0  ...
6054         8.4           35.0          17.0          13.0  ...
...          ...            ...           ...           ...  ...
142298      11.0           35.0           9.0          20.0  ...
142299       8.6           37.0          13.0          11.0  ...
142300      11.0           33.0          17.0          11.0  ...
142301      10.6           26.0           9.0          17.0  ...
142302      10.7           30.0          15.0           7.0  ...

        WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_SSW  \
6049           False          False           False           False
6050           False          False            True           False
6052           False          False           False           False
6053           False          False           False           False
6054           False          False           False           False
...              ...            ...             ...             ...
142298         False          False           False           False
142299         False           True           False           False
142300         False          False           False           False
142301         False          False           False           False
142302         False          False           False           False

        WindDir3pm_SW  WindDir3pm_W  WindDir3pm_WNW  WindDir3pm_WSW  \
6049             True         False           False           False
6050            False         False           False           False
6052            False         False           False           False
6053            False         False           False            True
6054            False         False            True           False
...               ...           ...             ...             ...
142298          False         False           False           False
142299          False         False           False           False
142300          False          True           False           False
142301          False         False           False           False
142302          False         False           False           False

        RainToday_Yes  RainTomorrow_Yes
6049            False             False
6050            False             False
6052            False             False
6053            False             False
6054            False             False
...               ...               ...
142298          False             False
142299          False             False
142300          False             False
142301          False             False
142302          False             False

[56420 rows x 65 columns]

In [34]:
x= df.iloc[:,1 :-1]

In [35]:
x

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,RainToday_Yes
6049,4,17.9,35.2,0.0,12.0,12.3,48.0,6.0,20.0,20.0,...,False,False,False,False,False,True,False,False,False,False
6050,4,18.4,28.9,0.0,14.8,13.0,37.0,19.0,19.0,30.0,...,False,False,False,True,False,False,False,False,False,False
6052,4,19.4,37.6,0.0,10.8,10.6,46.0,30.0,15.0,42.0,...,False,False,False,False,False,False,False,False,False,False
6053,4,21.9,38.4,0.0,11.4,12.2,31.0,6.0,6.0,37.0,...,False,False,False,False,False,False,False,False,True,False
6054,4,24.2,41.0,0.0,11.2,8.4,35.0,17.0,13.0,19.0,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,6,19.3,33.4,0.0,6.0,11.0,35.0,9.0,20.0,63.0,...,False,False,False,False,False,False,False,False,False,False
142299,6,21.2,32.6,0.0,7.6,8.6,37.0,13.0,11.0,56.0,...,False,False,True,False,False,False,False,False,False,False
142300,6,20.7,32.8,0.0,5.6,11.0,33.0,17.0,11.0,46.0,...,False,False,False,False,False,False,True,False,False,False
142301,6,19.5,31.8,0.0,6.2,10.6,26.0,9.0,17.0,62.0,...,False,False,False,False,False,False,False,False,False,False
142302,6,20.2,31.7,0.0,5.6,10.7,30.0,15.0,7.0,73.0,...,False,False,False,False,False,False,False,False,False,False

In [36]:
y = df.iloc[:, -1]

In [37]:
y

6049      False
6050      False
6052      False
6053      False
6054      False
          ...
142298    False
142299    False
142300    False
142301    False
142302    False
Name: RainTomorrow_Yes, Length: 56420, dtype: bool

In [39]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [42]:
x_scaled

array([[-1.18184371,  0.69120848,  1.57529783, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-1.18184371,  0.76913098,  0.67150378, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-1.18184371,  0.92497598,  1.91960032, ..., -0.24520965,
        -0.27084717, -0.53244519],
       ...,
       [-0.90791487,  1.12757448,  1.23099533, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-0.90791487,  0.94056048,  1.08753596, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-0.90791487,  1.04965198,  1.07319002, ..., -0.24520965,
        -0.27084717, -0.53244519]])

In [43]:
x=x_scaled

In [44]:
x

array([[-1.18184371,  0.69120848,  1.57529783, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-1.18184371,  0.76913098,  0.67150378, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-1.18184371,  0.92497598,  1.91960032, ..., -0.24520965,
        -0.27084717, -0.53244519],
       ...,
       [-0.90791487,  1.12757448,  1.23099533, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-0.90791487,  0.94056048,  1.08753596, ..., -0.24520965,
        -0.27084717, -0.53244519],
       [-0.90791487,  1.04965198,  1.07319002, ..., -0.24520965,
        -0.27084717, -0.53244519]])

In [45]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [65]:
# Initialize weights and bias
weights = np.zeros(x.shape[1])

In [66]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [67]:
def compute_cost(x, y, weights):
    m = len(y)
    h = sigmoid(np.dot(x, weights))
    cost = -(1/m) * np.sum(y * np.log(h) + (1-y) * np.log(1-h))
    return cost

In [71]:
def gradient_descent(x, y, weights, learning_rate, epochs):
    m = len(y)
    
    for epoch in range(epochs):
        h = sigmoid(np.dot(x, weights))
        gradient = np.dot(x.T, (h - y)) / m
        weights -= learning_rate * gradient
        
        cost = compute_cost(x, y, weights)
        if epoch % 100 == 0:
            print(f'Epoch {epoch}, Cost: {cost}')
    
    return weights

In [72]:
learning_rate = 0.01
epochs = 1000
# Train the logistic regression model using gradient descent
trained_weights = gradient_descent(x, y, weights, learning_rate, epochs)

Epoch 0, Cost: 0.6910795392841298
Epoch 100, Cost: 0.6003208606414684
Epoch 200, Cost: 0.5807331218321294
Epoch 300, Cost: 0.5734769279207025
Epoch 400, Cost: 0.5695708520310835
Epoch 500, Cost: 0.5668899175413145
Epoch 600, Cost: 0.5647888205238994
Epoch 700, Cost: 0.5630313458739521
Epoch 800, Cost: 0.5615135446800701
Epoch 900, Cost: 0.5601801900845377

In [74]:
print('Trained Weights:', trained_weights)

Trained Weights: [-1.54794513e-02  2.32931881e-02 -1.34464105e-02  1.96497863e-01
 -1.70898371e-03 -3.36696781e-01  2.73311088e-01  7.51802990e-03
 -7.42014729e-02  7.30784060e-02  4.08697351e-01 -1.38276770e-01
 -2.04221994e-01  2.91722009e-03  1.58034214e-01  4.31674582e-02
 -7.26321772e-02 -1.26166489e-02  1.00643140e-02 -1.65556372e-02
 -1.04367917e-03  4.69213358e-03  2.68561899e-05  3.57311010e-03
 -2.73549242e-03  9.17197517e-03  9.66552751e-03  1.73152863e-03
 -4.17372646e-03 -4.87101419e-03  1.19084382e-02  1.23740851e-03
  3.99218288e-02 -7.75745987e-03  3.51744470e-02  4.04130052e-02
  6.36113802e-02 -4.22464423e-03 -7.08942728e-03 -3.40270612e-02
 -2.73407058e-02 -2.58252618e-02 -3.46221476e-02 -2.21989046e-02
 -1.56287669e-02 -1.26999800e-02 -2.58719567e-02 -1.24576489e-02
  1.57242646e-03  2.67244834e-02  4.13971985e-03  2.80869934e-02
  2.47933520e-02  2.98680560e-02 -1.88906909e-02  4.92655861e-03
 -1.65477433e-03 -1.52399121e-02 -3.63218160e-02 -4.68350326e-03
  2.54745488e-02 -2.77854577e-02  1.42698912e-01]

In [81]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression


# Replace with your logistic regression model
model = LogisticRegression()
model.fit(x_train, y_train)

# Predictions for training and testing sets
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

# Compute accuracy
accuracy_train = accuracy_score(y_train, y_train_pred)
accuracy_test = accuracy_score(y_test, y_test_pred)

print(f'Training Accuracy: {accuracy_train}')
print(f'Testing Accuracy: {accuracy_test}')

Training Accuracy: 0.8551488833746899
Testing Accuracy: 0.857851825593761

In [82]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Compute precision, recall, and F1 score for training set
precision_train = precision_score(y_train, y_train_pred)
recall_train = recall_score(y_train, y_train_pred)
f1_train = f1_score(y_train, y_train_pred)

# Compute precision, recall, and F1 score for testing set
precision_test = precision_score(y_test, y_test_pred)
recall_test = recall_score(y_test, y_test_pred)
f1_test = f1_score(y_test, y_test_pred)

print(f'Training Precision: {precision_train}')
print(f'Training Recall: {recall_train}')
print(f'Training F1 Score: {f1_train}')

print(f'Testing Precision: {precision_test}')
print(f'Testing Recall: {recall_test}')
print(f'Testing F1 Score: {f1_test}')

Training Precision: 0.7294418980857375
Training Recall: 0.5442566887950111
Training F1 Score: 0.6233870967741936
Testing Precision: 0.7413698630136987
Testing Recall: 0.544466800804829
Testing F1 Score: 0.6278422273781903